defaults: &defaults
  host: localhost
  use_utc: false
  use_activesupport_time_zone: true
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: timemaster

test:
  <<: *defaults
  database: timemaster_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: timemaster